//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReminderXamarin.Resx {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ReminderXamarin.Resx.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string AchievementName {
            get {
                return ResourceManager.GetString("AchievementName", resourceCulture);
            }
        }
        
        internal static string Achievements {
            get {
                return ResourceManager.GetString("Achievements", resourceCulture);
            }
        }
        
        internal static string AchievementsCount {
            get {
                return ResourceManager.GetString("AchievementsCount", resourceCulture);
            }
        }
        
        internal static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        internal static string AddStep {
            get {
                return ResourceManager.GetString("AddStep", resourceCulture);
            }
        }
        
        internal static string AllNotes {
            get {
                return ResourceManager.GetString("AllNotes", resourceCulture);
            }
        }
        
        internal static string AlreadyHaveAccountQuestion {
            get {
                return ResourceManager.GetString("AlreadyHaveAccountQuestion", resourceCulture);
            }
        }
        
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        internal static string Birthday {
            get {
                return ResourceManager.GetString("Birthday", resourceCulture);
            }
        }
        
        internal static string Birthdays {
            get {
                return ResourceManager.GetString("Birthdays", resourceCulture);
            }
        }
        
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        internal static string CheckPasswordErrorMessage {
            get {
                return ResourceManager.GetString("CheckPasswordErrorMessage", resourceCulture);
            }
        }
        
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        internal static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        internal static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        internal static string ConfirmPin {
            get {
                return ResourceManager.GetString("ConfirmPin", resourceCulture);
            }
        }
        
        internal static string CreateAchievement {
            get {
                return ResourceManager.GetString("CreateAchievement", resourceCulture);
            }
        }
        
        internal static string CreateNote {
            get {
                return ResourceManager.GetString("CreateNote", resourceCulture);
            }
        }
        
        internal static string CreateToDo {
            get {
                return ResourceManager.GetString("CreateToDo", resourceCulture);
            }
        }
        
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        internal static string DeleteGalleryItemQuestion {
            get {
                return ResourceManager.GetString("DeleteGalleryItemQuestion", resourceCulture);
            }
        }
        
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        internal static string DescriptionPlaceholder {
            get {
                return ResourceManager.GetString("DescriptionPlaceholder", resourceCulture);
            }
        }
        
        internal static string DontHaveAccountQuestion {
            get {
                return ResourceManager.GetString("DontHaveAccountQuestion", resourceCulture);
            }
        }
        
        internal static string EditAchievement {
            get {
                return ResourceManager.GetString("EditAchievement", resourceCulture);
            }
        }
        
        internal static string EditBirthdayDate {
            get {
                return ResourceManager.GetString("EditBirthdayDate", resourceCulture);
            }
        }
        
        internal static string EditName {
            get {
                return ResourceManager.GetString("EditName", resourceCulture);
            }
        }
        
        internal static string EditPreferencesDescription {
            get {
                return ResourceManager.GetString("EditPreferencesDescription", resourceCulture);
            }
        }
        
        internal static string EnterPin {
            get {
                return ResourceManager.GetString("EnterPin", resourceCulture);
            }
        }
        
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        internal static string FriendName {
            get {
                return ResourceManager.GetString("FriendName", resourceCulture);
            }
        }
        
        internal static string FriendsBirthdaysCount {
            get {
                return ResourceManager.GetString("FriendsBirthdaysCount", resourceCulture);
            }
        }
        
        internal static string Gallery {
            get {
                return ResourceManager.GetString("Gallery", resourceCulture);
            }
        }
        
        internal static string High {
            get {
                return ResourceManager.GetString("High", resourceCulture);
            }
        }
        
        internal static string Images {
            get {
                return ResourceManager.GetString("Images", resourceCulture);
            }
        }
        
        internal static string IncorrectData {
            get {
                return ResourceManager.GetString("IncorrectData", resourceCulture);
            }
        }
        
        internal static string LoadingMessage {
            get {
                return ResourceManager.GetString("LoadingMessage", resourceCulture);
            }
        }
        
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        internal static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        internal static string Low {
            get {
                return ResourceManager.GetString("Low", resourceCulture);
            }
        }
        
        internal static string Medium {
            get {
                return ResourceManager.GetString("Medium", resourceCulture);
            }
        }
        
        internal static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        internal static string MinimumLengthThreeSymbolsMessage {
            get {
                return ResourceManager.GetString("MinimumLengthThreeSymbolsMessage", resourceCulture);
            }
        }
        
        internal static string NewStep {
            get {
                return ResourceManager.GetString("NewStep", resourceCulture);
            }
        }
        
        internal static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        internal static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        internal static string NotesCount {
            get {
                return ResourceManager.GetString("NotesCount", resourceCulture);
            }
        }
        
        internal static string NotesPlaceholder {
            get {
                return ResourceManager.GetString("NotesPlaceholder", resourceCulture);
            }
        }
        
        internal static string NotesTitle {
            get {
                return ResourceManager.GetString("NotesTitle", resourceCulture);
            }
        }
        
        internal static string NoteText {
            get {
                return ResourceManager.GetString("NoteText", resourceCulture);
            }
        }
        
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        internal static string PickImageForAchievement {
            get {
                return ResourceManager.GetString("PickImageForAchievement", resourceCulture);
            }
        }
        
        internal static string PickPhoto {
            get {
                return ResourceManager.GetString("PickPhoto", resourceCulture);
            }
        }
        
        internal static string PickVideo {
            get {
                return ResourceManager.GetString("PickVideo", resourceCulture);
            }
        }
        
        internal static string PinDoesNotMatchMessage {
            get {
                return ResourceManager.GetString("PinDoesNotMatchMessage", resourceCulture);
            }
        }
        
        internal static string PinSavedMessage {
            get {
                return ResourceManager.GetString("PinSavedMessage", resourceCulture);
            }
        }
        
        internal static string PreferencesDescription {
            get {
                return ResourceManager.GetString("PreferencesDescription", resourceCulture);
            }
        }
        
        internal static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        internal static string SettingsLoginSectionName {
            get {
                return ResourceManager.GetString("SettingsLoginSectionName", resourceCulture);
            }
        }
        
        internal static string SettingsThemeSectionName {
            get {
                return ResourceManager.GetString("SettingsThemeSectionName", resourceCulture);
            }
        }
        
        internal static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        internal static string StepName {
            get {
                return ResourceManager.GetString("StepName", resourceCulture);
            }
        }
        
        internal static string Steps {
            get {
                return ResourceManager.GetString("Steps", resourceCulture);
            }
        }
        
        internal static string StepTimeEstimation {
            get {
                return ResourceManager.GetString("StepTimeEstimation", resourceCulture);
            }
        }
        
        internal static string StepType {
            get {
                return ResourceManager.GetString("StepType", resourceCulture);
            }
        }
        
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        internal static string TakePhoto {
            get {
                return ResourceManager.GetString("TakePhoto", resourceCulture);
            }
        }
        
        internal static string TakeVideo {
            get {
                return ResourceManager.GetString("TakeVideo", resourceCulture);
            }
        }
        
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        internal static string TimeSpent {
            get {
                return ResourceManager.GetString("TimeSpent", resourceCulture);
            }
        }
        
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        internal static string TitlePlaceholder {
            get {
                return ResourceManager.GetString("TitlePlaceholder", resourceCulture);
            }
        }
        
        internal static string ToDoSection {
            get {
                return ResourceManager.GetString("ToDoSection", resourceCulture);
            }
        }
        
        internal static string UseColorTheme {
            get {
                return ResourceManager.GetString("UseColorTheme", resourceCulture);
            }
        }
        
        internal static string UsePin {
            get {
                return ResourceManager.GetString("UsePin", resourceCulture);
            }
        }
        
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        internal static string UseSafeMode {
            get {
                return ResourceManager.GetString("UseSafeMode", resourceCulture);
            }
        }
        
        internal static string Videos {
            get {
                return ResourceManager.GetString("Videos", resourceCulture);
            }
        }
    }
}
